---
Name: silverware-testimonials
---

# Configure Testimonial Page Controller:

SilverWare\Testimonials\Pages\TestimonialPageController:
  required_js:
    - "silverware/testimonials: client/dist/js/bundle.js"
  required_css:
    - "silverware/testimonials: client/dist/styles/bundle.css"
